"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url
from datetime import timedelta # Importamos esto para configurar la duración del token

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-default-key-for-dev')

# SECURITY WARNING: don't run with debug turned on in production!
# En Render, la variable de entorno 'RENDER' se establece en 'true'.
# DEBUG será True localmente y False en producción.
DEBUG = 'RENDER' not in os.environ

# Los hosts permitidos se leen de una variable de entorno.
ALLOWED_HOSTS = ['localhost', '127.0.0.1']

RENDER_EXTERNAL_HOSTNAME = os.environ.get('RENDER_EXTERNAL_HOSTNAME')
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)
    
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # --- LIBRERÍAS DE TERCEROS ---
    'rest_framework',           # Habilita la API
    'rest_framework_simplejwt', # Habilita la autenticación por tokens
    'corsheaders',              # Habilita conexiones desde otros dominios (React)
    'whitenoise',               # Para servir archivos estáticos en producción
    
    # --- MIS APLICACIONES ---
    'core_bancario',            # Nuestra lógica del banco


]
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware', 
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    # WhiteNoise para servir archivos estáticos en producción
    'whitenoise.middleware.WhiteNoiseMiddleware',    
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# --- CONFIGURACIÓN DE CORS (Conexión Frontend-Backend) ---
# Definimos quién tiene permiso de hablar con nuestro banco.
# En producción, lee las URLs permitidas desde una variable de entorno.
CORS_ALLOWED_ORIGINS = [
    "https://wholabank-front.onrender.com",
    "http://localhost:5173", # Para tus pruebas locales con Vite
]

CSRF_TRUSTED_ORIGINS = ["https://wholabank-front.onrender.com"]

# --- CONFIGURACIÓN DE DRF (Django Rest Framework) ---
REST_FRAMEWORK = {
    # Definimos que la autenticación por defecto sea vía JWT (Tokens)
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    # Por defecto, bloqueamos todo. Solo usuarios autenticados pueden ver datos.
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}

# --- CONFIGURACIÓN DE JWT (Simple JWT) ---
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60), # El token dura 1 hora (seguridad bancaria)
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),    # Token para renovar sesión dura 1 día
    'ROTATE_REFRESH_TOKENS': True,                  # Cambiar el token de refresh al usarlo (mayor seguridad)
}

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
DATABASE_URL = os.environ.get('DATABASE_URL')

if DATABASE_URL:
    # Configuración para producción (ej. PostgreSQL en Render).
    # dj_database_url.config() leerá automáticamente la variable DATABASE_URL.
    DATABASES = {
        'default': dj_database_url.config(conn_max_age=600)
    }
else:
    # Configuración para desarrollo local (SQLite) si DATABASE_URL no está definida.
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
# Configuración para WhiteNoise
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# --- CONFIGURACIONES PERSONALIZADAS DE LA APP ---
MI_CODIGO_BANCO = "0001"    # Código de nuestro banco (dígitos 1-4 de la cuenta)
MI_CODIGO_AGENCIA = "0001"  # Código de nuestra agencia principal (dígitos 5-8 de la cuenta)
MI_BIN_TARJETA = "00001"    # BIN de nuestras tarjetas (dígitos 2-6)
