# Generated by Django 6.0 on 2026-02-16 15:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Directorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Ej: 0002 para Banco 2', max_length=10, unique=True)),
                ('nombre', models.CharField(help_text='Ej: BANCO_2', max_length=50)),
                ('rif', models.CharField(blank=True, help_text='J-12345678-9', max_length=20, null=True)),
                ('tipo', models.CharField(choices=[('BANCO', 'Banco'), ('COMERCIO', 'Comercio')], max_length=10)),
                ('api_url', models.URLField(help_text='Endpoint base del equipo. Ej: http://192.168.1.50:8000/api/')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_persona', models.CharField(choices=[('NATURAL', 'Persona Natural'), ('JURIDICO', 'Persona Jurídica')], default='NATURAL', max_length=10)),
                ('cedula', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('rif', models.CharField(max_length=20, unique=True)),
                ('telefono', models.CharField(max_length=20)),
                ('fecha_nacimiento', models.DateField(null=True)),
                ('lugar_nacimiento', models.CharField(default='Venezuela', max_length=100)),
                ('estado_civil', models.CharField(blank=True, max_length=20, null=True)),
                ('profesion', models.CharField(default='Computación', max_length=50)),
                ('origen_fondos', models.CharField(default='Actividad Comercial', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cuenta', models.CharField(editable=False, max_length=20, unique=True)),
                ('saldo', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('tipo_cuenta', models.CharField(choices=[('CORRIENTE', 'Corriente'), ('AHORRO', 'Ahorro')], default='CORRIENTE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuentas', to='core_bancario.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Comercio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_identificador', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('cuenta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_comercio', to='core_bancario.cuenta')),
            ],
        ),
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=16, unique=True)),
                ('cvv', models.CharField(editable=False, max_length=3)),
                ('fecha_vencimiento', models.CharField(editable=False, max_length=5)),
                ('estado', models.BooleanField(default=True)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarjetas', to='core_bancario.cuenta')),
            ],
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PAGO_COMERCIO', 'Pago en Comercio'), ('TRANSFERENCIA', 'Transferencia')], max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=15)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('referencia_externa', models.CharField(blank=True, max_length=100, null=True)),
                ('banco_emisor_id', models.CharField(max_length=10)),
                ('estado', models.CharField(choices=[('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], max_length=20)),
                ('codigo_respuesta', models.CharField(max_length=20)),
                ('mensaje_error', models.TextField(blank=True, null=True)),
                ('cuenta_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creditos', to='core_bancario.cuenta')),
                ('cuenta_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debitos', to='core_bancario.cuenta')),
            ],
        ),
    ]
