# Generated by Django 6.0 on 2026-02-16 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_bancario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='directorio',
            name='rif',
            field=models.CharField(blank=True, help_text='J-12345678-9', max_length=20, null=True),
        ),
    ]
