# Generated by Django 6.0 on 2026-02-21 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_bancario', '0002_directorio_rif'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminDashboardProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Panel de Control del Banco',
                'verbose_name_plural': 'Panel de Control del Banco',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core_bancario.cliente',),
        ),
    ]
