# Generated by Django 6.0 on 2026-02-26 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_bancario', '0003_admindashboardproxy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=1000.0, max_digits=15),
        ),
    ]
