# Generated by Django 6.0 on 2026-03-20 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_bancario', '0004_alter_cuenta_saldo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='bono_reclamado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
