# Generated by Django 6.0 on 2026-03-20 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_bancario', '0005_cliente_bono_reclamado_alter_cuenta_saldo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionGlobal',
            fields=[
                ('clave', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('valor', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='tipo',
            field=models.CharField(choices=[('PAGO_COMERCIO', 'Pago en Comercio'), ('TRANSFERENCIA', 'Transferencia'), ('PAGO_INTERBANCARIO', 'Pago Interbancario'), ('COMISION_BANCARIA', 'Comisión Bancaria')], max_length=20),
        ),
    ]
