# Generated by Django 6.0 on 2026-03-22 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_bancario', '0006_configuracionglobal_alter_transaccion_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarjeta',
            name='dia_corte',
            field=models.IntegerField(default=15, help_text='Día del mes en que cierra la facturación'),
        ),
        migrations.AddField(
            model_name='tarjeta',
            name='dia_pago',
            field=models.IntegerField(default=5, help_text='Día del mes límite para pagar'),
        ),
        migrations.AddField(
            model_name='tarjeta',
            name='limite_credito',
            field=models.DecimalField(decimal_places=2, default=10000.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='tarjeta',
            name='saldo_disponible',
            field=models.DecimalField(decimal_places=2, default=10000.0, max_digits=15),
        ),
    ]
