name: Build and deploy Python app to Azure Web App - wholabank-app

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.14'
          cache: 'pip' # Activa la caché para pip

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm' # Activa la caché para npm
          cache-dependency-path: frontend/package-lock.json

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Install frontend dependencies and build
        working-directory: ./frontend
        run: |
          npm install
          npm run build
      
      - name: Create optimized deployment artifact
        run: |
          mkdir -p staging
          cp -r backend staging/
          cp requirements.txt staging/
          # La estructura frontend/dist es necesaria para que collectstatic la encuentre
          mkdir -p staging/frontend
          cp -r frontend/dist staging/frontend/
      
      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: staging/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_E487EE6A07E94AA08754C7E203274F55 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_45E4B0FE848543F7B4FE7C057439E74E }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_967DED126BDD46BC9106290FEB8BBDA2 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'wholabank-app'
          slot-name: 'Production'
          package: .